# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 573)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 90, 561, 121))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 473, 66))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 0, 2, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout.addWidget(self.checkBox_10, 0, 8, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 2, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 2, 2, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 0, 4, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 2, 4, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout.addWidget(self.checkBox_9, 0, 6, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout.addWidget(self.checkBox_8, 2, 8, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 2, 6, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 0, 7, 1, 1)
        self.widget = QtWidgets.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(30, 30, 201, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.tabWidget.addTab(self.tab_2, "")
        self.tabConfig = QtWidgets.QWidget()
        self.tabConfig.setObjectName("tabConfig")
        self.pushButton_3 = QtWidgets.QPushButton(self.tabConfig)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 440, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabConfig)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 20, 721, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget1 = QtWidgets.QWidget(self.groupBox_2)
        self.widget1.setGeometry(QtCore.QRect(30, 30, 561, 54))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.tdxDirLineEdit = QtWidgets.QLineEdit(self.widget1)
        self.tdxDirLineEdit.setObjectName("tdxDirLineEdit")
        self.gridLayout_2.addWidget(self.tdxDirLineEdit, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.tdxDirLineEdit_2 = QtWidgets.QLineEdit(self.widget1)
        self.tdxDirLineEdit_2.setObjectName("tdxDirLineEdit_2")
        self.gridLayout_2.addWidget(self.tdxDirLineEdit_2, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 1, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabConfig)
        self.groupBox_3.setGeometry(QtCore.QRect(29, 150, 711, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.widget2 = QtWidgets.QWidget(self.groupBox_3)
        self.widget2.setGeometry(QtCore.QRect(30, 60, 561, 25))
        self.widget2.setObjectName("widget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.widget2)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.dataDirLineEdit = QtWidgets.QLineEdit(self.widget2)
        self.dataDirLineEdit.setObjectName("dataDirLineEdit")
        self.gridLayout_3.addWidget(self.dataDirLineEdit, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 2, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_11.setGeometry(QtCore.QRect(30, 30, 121, 16))
        self.checkBox_11.setObjectName("checkBox_11")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabConfig)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 280, 711, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_12.setGeometry(QtCore.QRect(30, 30, 141, 16))
        self.checkBox_12.setObjectName("checkBox_12")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_5.setGeometry(QtCore.QRect(560, 70, 101, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.widget3 = QtWidgets.QWidget(self.groupBox_4)
        self.widget3.setGeometry(QtCore.QRect(30, 60, 501, 48))
        self.widget3.setObjectName("widget3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_4.addWidget(self.lineEdit_4, 1, 4, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_4.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_4.addWidget(self.lineEdit_2, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tabConfig, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数据导入工具"))
        self.groupBox.setTitle(_translate("MainWindow", "数据预加载设置"))
        self.checkBox.setText(_translate("MainWindow", "日线"))
        self.checkBox_2.setText(_translate("MainWindow", "周线"))
        self.checkBox_10.setText(_translate("MainWindow", "年线"))
        self.checkBox_4.setText(_translate("MainWindow", "1分钟线"))
        self.checkBox_5.setText(_translate("MainWindow", "5分钟线"))
        self.checkBox_3.setText(_translate("MainWindow", "月线"))
        self.checkBox_6.setText(_translate("MainWindow", "15分钟线"))
        self.checkBox_9.setText(_translate("MainWindow", "半年线"))
        self.checkBox_8.setText(_translate("MainWindow", "60分钟线"))
        self.checkBox_7.setText(_translate("MainWindow", "30分钟线"))
        self.label_8.setText(_translate("MainWindow", "使用数据库引擎："))
        self.comboBox.setItemText(0, _translate("MainWindow", "HDF5"))
        self.comboBox.setItemText(1, _translate("MainWindow", "MYSQL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "数据引擎设置"))
        self.pushButton_3.setText(_translate("MainWindow", "保存设置"))
        self.groupBox_2.setTitle(_translate("MainWindow", "盘后数据源（至少需配置一个，也可两个同时配置）："))
        self.label_2.setText(_translate("MainWindow", "通达信盘后数据目录："))
        self.pushButton_2.setText(_translate("MainWindow", "选择"))
        self.label_3.setText(_translate("MainWindow", "大智慧盘后数据目录："))
        self.pushButton_4.setText(_translate("MainWindow", "选择"))
        self.groupBox_3.setTitle(_translate("MainWindow", "HDF5保存数据设置"))
        self.label.setText(_translate("MainWindow", "目标数据（HDF5）存放目录："))
        self.pushButton.setText(_translate("MainWindow", "选择"))
        self.checkBox_11.setText(_translate("MainWindow", "使用HDF5保存数据"))
        self.groupBox_4.setTitle(_translate("MainWindow", "MYSQL保存数据设置"))
        self.checkBox_12.setText(_translate("MainWindow", "使用MYSQL保存数据"))
        self.pushButton_5.setText(_translate("MainWindow", "测试数据库连接"))
        self.label_7.setText(_translate("MainWindow", "密码："))
        self.label_4.setText(_translate("MainWindow", "ip地址："))
        self.label_6.setText(_translate("MainWindow", "用户名："))
        self.label_5.setText(_translate("MainWindow", "端口："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConfig), _translate("MainWindow", "数据导入配置"))

