add_requires("doctest")

function coverage_report(target)
    if is_mode("coverage") and not is_plat("windows") and not (linuxos.name() == "ubuntu" and linuxos.version():lt("20.0")) then 
        -- For branch coverage, add: --rc lcov_branch_coverage=1 to both the lcov and genhtml commands below
        print("Processing coverage info ...")
        
        if not os.isfile("cover-init.info") then
            -- Initialize and create the baseline data file
            os.run("lcov -c -i -d ./ -o cover-init.info") 
        end

        -- Remove the previous results, otherwise it is error-prone
        os.tryrm('cover.info')
        os.tryrm('cover-total.info')

        -- Collect the coverage files produced by running the current test files
        os.run("lcov -c -d ./ -o cover.info")

        -- Merge the baseline data and the coverage data generated by running the test files
        os.exec("lcov --ignore-errors empty --rc geninfo_unexecuted_blocks=1 -a cover-init.info -a cover.info -o cover-total.info")

        -- Remove the following code or files from the statistics (regex supported)
        os.exec("lcov --ignore-errors unused --remove cover-total.info '*/usr/include/*' \
                '*/usr/lib/*' '*/usr/local/include/*' '*/usr/local/lib/*' '*/usr/local/lib64/*' \
                '*/.xmake*' '*/boost/*' \
                'unit_test/*' 'hikyuu/data_driver/*' 'hikyuu/global/*' 'hikyuu/plugin/*' 'hikyuu/utilities/*' \
                -o cover-final.info")
        
        -- The directory name of the generated html and related files, --legend shows a simple statistics description
        os.exec("genhtml -o cover_report --legend --title 'hikyuu' cover-final.info")

        -- Generate the report readable by sonar
        if is_plat("linux") then
            os.run("gcovr -r . -e cpp/test --xml -o coverage.xml")
        end
    end
end

function prepare_run(target)
    local targetname = target:name()
  
    if "unit-test" == targetname or "small-test" == targetname or "prepare-test" == targetname then
      print("copying test_data ...")
      os.rm("$(builddir)/$(mode)/$(plat)/$(arch)/lib/test_data")
      os.cp("$(projectdir)/test_data", "$(builddir)/$(mode)/$(plat)/$(arch)/lib/")
      os.cp("$(projectdir)/hikyuu/plugin", "$(builddir)/$(mode)/$(plat)/$(arch)/lib/")
      os.cp("$(projectdir)/i18n", "$(builddir)/$(mode)/$(plat)/$(arch)/lib/")
      print("copy finished")
    end
end


target("unit-test")
    set_kind("binary")
    set_default(false)

    if is_mode("coverage") then 
        add_cxflags("-fprofile-update=atomic")
    end    

    if get_config("leak_check") then
        if is_plat("macosx") then
            set_policy("build.sanitizer.address", true)
        elseif is_plat("linux") then
            -- Requires export LD_PRELOAD=libasan.so
            -- May also need to suppress the openssl leak warnings: export LSAN_OPTIONS="suppressions=asan.sup"
            -- The asan.sup must be copied to the unit-test execution directory
            set_policy("build.sanitizer.address", true)
            set_policy("build.sanitizer.leak", true)
            -- set_policy("build.sanitizer.memory", true)
            -- set_policy("build.sanitizer.thread", true)
        end
    end

    if has_config("mysql") and not has_config("disable_libmysqlclient") then
        add_packages("mysql")
    end    


    add_packages("boost", "fmt", "spdlog", "doctest", "sqlite3", "nlohmann_json", "tl_expected", "eigen", "nng")
    if has_config("ta_lib") then
        add_packages("ta-lib")
    end

    add_includedirs("..")

    if is_plat("windows") then
        add_cxflags("/bigobj")
        add_cxflags("-wd4267", "-wd4996", "-wd4251", "-wd4244", "-wd4805", "-wd4566")
    else
        add_cxflags("-Wno-unused-variable",  "-Wno-missing-braces")
        add_cxflags("-Wno-sign-compare", "-Wno-self-assign-overloaded")
    end
    
    if is_plat("windows") and get_config("kind") == "shared" then
        add_defines("HKU_API=__declspec(dllimport)")
        add_defines("HKU_UTILS_API=__declspec(dllimport)")
    end

    add_deps("hikyuu")

    if is_plat("linux") or is_plat("macosx") then
        add_links("sqlite3")
        add_shflags("-Wl,-rpath=$ORIGIN", "-Wl,-rpath=$ORIGIN/../lib")
    end

    if is_plat("macosx") then
        -- Required by the boost serialization
        add_cxflags("-frtti -fvisibility=default")
        add_ldflags("-Wl,-flat_namespace,-undefined,dynamic_lookup")
    end

    -- set_policy("build.optimization.lto", true)
    add_rules("c++.unity_build", {batchsize = 0})
    add_files("./hikyuu/**.cpp|real_data/**|indicator_talib/**.cpp")
    
    add_files("./hikyuu/analysis/**.cpp", {unity_group="analysis"})
    add_files("./hikyuu/hikyuu/**.cpp", {unity_group="hikyuu"})
    add_files("./hikyuu/indicator/**.cpp", {unity_group="indicator"})
    add_files("./hikyuu/factor/**.cpp", {unity_group="factor"})
    add_files("./hikyuu/serialization/**.cpp", {unity_group="serialization"})
    add_files("./hikyuu/trade_manage/**.cpp", {unity_group="trade_manage"})
    add_files("./hikyuu/trade_sys/condition/**.cpp", {unity_group="condition"})
    add_files("./hikyuu/trade_sys/environment/**.cpp", {unity_group="environment"})
    add_files("./hikyuu/trade_sys/moneymanager/**.cpp", {unity_group="moneymanager"})
    add_files("./hikyuu/trade_sys/multifactor/**.cpp|test_style_regression.cpp", {unity_group="multifactor"})
    -- The test includes the Eigen headers, compile it separately to avoid the unity build leaking the Eigen inline implementations
    add_files("./hikyuu/trade_sys/multifactor/test_style_regression.cpp", {unity_group = false})
    add_files("./hikyuu/trade_sys/profitgoal/**.cpp", {unity_group="profitgoal"})
    add_files("./hikyuu/trade_sys/selector/**.cpp", {unity_group="selector"})
    add_files("./hikyuu/trade_sys/signal/**.cpp", {unity_group="signal"})
    add_files("./hikyuu/trade_sys/slippage/**.cpp", {unity_group="slippage"})
    add_files("./hikyuu/trade_sys/stoploss/**.cpp", {unity_group="stoploss"})
    add_files("./hikyuu/trade_sys/system/**.cpp", {unity_group="system"})
    add_files("./hikyuu/utilities/**.cpp", {unity_group="utilities"})

    if has_config("ta_lib") then
        add_files("hikyuu/indicator_talib/**.cpp", {unity_group="talib"})
    end

    before_run(prepare_run)
    after_run(coverage_report)
target_end()

target("small-test")
    set_kind("binary")
    set_default(false)
    
    if has_config("mysql") and not has_config("disable_libmysqlclient") then
        add_packages("mysql")
    end    

    add_packages("boost", "fmt", "spdlog", "doctest", "sqlite3", "nlohmann_json", "tl_expected", "nng")

    add_includedirs("..")

    if is_plat("windows") then
        add_cxflags("-wd4267")
        add_cxflags("-wd4251")
        add_cxflags("-wd4244")
        add_cxflags("-wd4805")
        add_cxflags("-wd4566")
    else
        add_cxflags("-Wno-unused-variable",  "-Wno-missing-braces")
        add_cxflags("-Wno-sign-compare")
    end
    
    if is_plat("windows") and get_config("kind") == "shared" then
        add_defines("HKU_API=__declspec(dllimport)")
        add_defines("HKU_UTILS_API=__declspec(dllimport)")
    end

    add_deps("hikyuu")

    if is_plat("linux") or is_plat("macosx") then
        add_shflags("-Wl,-rpath=$ORIGIN", "-Wl,-rpath=$ORIGIN/../lib")
    end

    -- add files
    add_files("./hikyuu/hikyuu/**.cpp");
    add_files("./hikyuu/*.cpp")

    before_run(prepare_run)
    after_run(coverage_report)
target_end()

target("real-test")
    set_kind("binary")
    set_default(false)

    if has_config("mysql") and not has_config("disable_libmysqlclient") then
        add_packages("mysql")
    end
    
    add_packages("boost", "fmt", "spdlog", "doctest", "sqlite3", "mysql", "nlohmann_json", "tl_expected", "nng")
    
    add_includedirs("..")

    if is_plat("windows") then
        add_cxflags("-wd4267", "-wd4996", "-wd4251", "-wd4244", "-wd4805", "-wd4566")
    else
        add_cxflags("-Wno-unused-variable",  "-Wno-missing-braces")
        add_cxflags("-Wno-sign-compare")
    end
    
    if is_plat("windows") and get_config("kind") == "shared" then
        add_defines("HKU_API=__declspec(dllimport)")
        add_defines("HKU_UTILS_API=__declspec(dllimport)")
    end

    add_defines("HKU_USE_REAL_DATA_TEST")
    add_deps("hikyuu")

    if is_plat("linux") or is_plat("macosx") then
        add_links("sqlite3")
        add_shflags("-Wl,-rpath=$ORIGIN", "-Wl,-rpath=$ORIGIN/../lib")
    end

    -- add files
    add_files("./hikyuu/real_data/**.cpp");
    add_files("./hikyuu/test_main.cpp")

    before_run(prepare_run)
    after_run(coverage_report)
target_end()
