/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the files COPYING and Copyright.html.  COPYING can be found at the root   *
 * of the source code distribution tree; Copyright.html can be found at the  *
 * root level of an installed copy of the electronic HDF5 document set and   *
 * is linked from the top-level documents page.  It can also be found at     *
 * http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have          *
 * access to either file, you may request a copy from help@hdfgroup.org.     *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */


#ifndef _H5f90i_gen_H
#define _H5f90i_gen_H

/* This file is automatically generated by H5match_types.c at build time. */

#include "H5public.h"

#define c_int_1 char
#define c_int_2 short
#define c_int_4 long
#define c_int_8 long long
#define c_float_4 float
#define c_float_8 long double

typedef c_int_8 haddr_t_f;
typedef c_int_8 hsize_t_f;
typedef c_int_8 hssize_t_f;
typedef c_int_8 size_t_f;
typedef c_int_4 int_f;
typedef c_int_1 int_1_f;
typedef c_int_2 int_2_f;
typedef c_int_4 int_4_f;
typedef c_int_8 int_8_f;
typedef c_float_4 real_4_f;
typedef c_float_8 real_8_f;
typedef c_float_8 real_16_f;
typedef c_int_4 hid_t_f;
typedef c_float_4 real_f;
typedef c_float_8 double_f;

#endif /* _H5f90i_gen_H */
