! * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
!   Copyright by The HDF Group.                                               *
!   Copyright by the Board of Trustees of the University of Illinois.         *
!   All rights reserved.                                                      *
!                                                                             *
!   This file is part of HDF5.  The full HDF5 copyright notice, including     *
!   terms governing use, modification, and redistribution, is contained in    *
!   the files COPYING and Copyright.html.  COPYING can be found at the root   *
!   of the source code distribution tree; Copyright.html can be found at the  *
!   root level of an installed copy of the electronic HDF5 document set and   *
!   is linked from the top-level documents page.  It can also be found at     *
!   http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have          *
!   access to either file, you may request a copy from help@hdfgroup.org.     *
! * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
!
!
! This file is automatically generated and contains HDF5 Fortran90 type definitions.
!
       MODULE H5FORTRAN_TYPES
         !
         !  HDF5 integers
         !
        INTEGER, PARAMETER :: HADDR_T = 8
        INTEGER, PARAMETER :: HSIZE_T = 8
        INTEGER, PARAMETER :: HSSIZE_T = 8
        INTEGER, PARAMETER :: SIZE_T = 8
        INTEGER, PARAMETER :: Fortran_INTEGER = 4
        INTEGER, PARAMETER :: Fortran_INTEGER_1 = 1
        INTEGER, PARAMETER :: Fortran_INTEGER_2 = 2
        INTEGER, PARAMETER :: Fortran_INTEGER_4 = 4
        INTEGER, PARAMETER :: Fortran_INTEGER_8 = 8
        INTEGER, PARAMETER :: Fortran_REAL_4 = 4
        INTEGER, PARAMETER :: Fortran_REAL_8 = 8
        INTEGER, PARAMETER :: Fortran_REAL_16 = 8
        INTEGER, PARAMETER :: HID_T = 4
        INTEGER, PARAMETER :: Fortran_REAL = 4
        INTEGER, PARAMETER :: Fortran_DOUBLE = 8
        INTEGER, PARAMETER :: H5R_DSET_REG_REF_BUF_SIZE_F = 12

        INTEGER(SIZE_T), PARAMETER :: OBJECT_NAMELEN_DEFAULT_F = -1

        END MODULE H5FORTRAN_TYPES
