# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from .waiting_resource import *


class HkuWaitingDialog(QtWidgets.QDialog):
    def __init__(self, parent):
        super(HkuWaitingDialog, self).__init__(parent)
        self.setObjectName("Waiting dialog")
        self.resize(284, 53)
        self.formLayout = QtWidgets.QFormLayout(self)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.label_text = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(50)
        self.label_text.setFont(font)
        self.label_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text.setObjectName("text")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label_text)

        _translate = QtCore.QCoreApplication.translate
        self.label_text.setText(_translate("HkuWaitingDialog", "Waiting..."))

        # 设置窗体透明度
        self.setWindowOpacity(0.9)

        # 设置背景透明
        #self.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        # 设置为对话框风格，并且去掉边框
        self.setWindowFlags(QtCore.Qt.Dialog | QtCore.Qt.FramelessWindowHint)

        # 设置为模态窗口
        self.setWindowModality(QtCore.Qt.WindowModal)

        self.label.setStyleSheet("background-color: transparent;")
        self.movie = QtGui.QMovie(":/gif/waiting.gif")
        self.label.setMovie(self.movie)
        self.label.setScaledContents(True)
        self.movie.start()

        #screen = parent.geometry()
        #self.move((screen.width() - self.width()) / 2 + 240, (screen.height() - self.height()) / 2)

        QtCore.QMetaObject.connectSlotsByName(self)

    def closeEvent(self, a0: QtGui.QCloseEvent) -> None:
        self.movie.stop()

    def setText(self, text):
        """设置等待提示信息"""
        self.label_text.setText(text)
