# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_HkuAddUserDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddUserDialog(object):
    def setupUi(self, AddUserDialog):
        AddUserDialog.setObjectName("AddUserDialog")
        AddUserDialog.resize(327, 179)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddUserDialog)
        self.buttonBox.setGeometry(QtCore.QRect(150, 130, 156, 23))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(AddUserDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 281, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.name_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.name_lineEdit.setMaxLength(100)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.gridLayout.addWidget(self.name_lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.password_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.password_lineEdit.setMaxLength(100)
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.gridLayout.addWidget(self.password_lineEdit, 1, 1, 1, 1)

        self.retranslateUi(AddUserDialog)
        self.buttonBox.accepted.connect(AddUserDialog.accept)
        self.buttonBox.rejected.connect(AddUserDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AddUserDialog)

    def retranslateUi(self, AddUserDialog):
        _translate = QtCore.QCoreApplication.translate
        AddUserDialog.setWindowTitle(_translate("AddUserDialog", "Add User"))
        self.label.setText(_translate("AddUserDialog", "User name"))
        self.label_2.setText(_translate("AddUserDialog", "password"))
