# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_HkuEditSessionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HkuEditSessionDialog(object):
    def setupUi(self, HkuEditSessionDialog):
        HkuEditSessionDialog.setObjectName("HkuEditSessionDialog")
        HkuEditSessionDialog.resize(562, 390)
        self.layoutWidget = QtWidgets.QWidget(HkuEditSessionDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 501, 298))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.host_label = QtWidgets.QLabel(self.layoutWidget)
        self.host_label.setObjectName("host_label")
        self.gridLayout.addWidget(self.host_label, 0, 0, 1, 1)
        self.ip_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.ip_lineEdit.setMaxLength(100)
        self.ip_lineEdit.setObjectName("ip_lineEdit")
        self.gridLayout.addWidget(self.ip_lineEdit, 0, 1, 1, 2)
        self.port_label = QtWidgets.QLabel(self.layoutWidget)
        self.port_label.setObjectName("port_label")
        self.gridLayout.addWidget(self.port_label, 1, 0, 1, 1)
        self.port_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.port_spinBox.setMaximum(65535)
        self.port_spinBox.setProperty("value", 9001)
        self.port_spinBox.setObjectName("port_spinBox")
        self.gridLayout.addWidget(self.port_spinBox, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.user_label = QtWidgets.QLabel(self.layoutWidget)
        self.user_label.setObjectName("user_label")
        self.gridLayout.addWidget(self.user_label, 2, 0, 1, 1)
        self.user_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.user_lineEdit.setMaxLength(100)
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.gridLayout.addWidget(self.user_lineEdit, 2, 1, 1, 2)
        self.password_label = QtWidgets.QLabel(self.layoutWidget)
        self.password_label.setObjectName("password_label")
        self.gridLayout.addWidget(self.password_label, 3, 0, 1, 1)
        self.password_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.password_lineEdit.setMaxLength(100)
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setPlaceholderText("")
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.gridLayout.addWidget(self.password_lineEdit, 3, 1, 1, 2)
        self.remark_label = QtWidgets.QLabel(self.layoutWidget)
        self.remark_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.remark_label.setObjectName("remark_label")
        self.gridLayout.addWidget(self.remark_label, 4, 0, 1, 1)
        self.remark_textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.remark_textEdit.setObjectName("remark_textEdit")
        self.gridLayout.addWidget(self.remark_textEdit, 4, 1, 1, 2)
        self.layoutWidget1 = QtWidgets.QWidget(HkuEditSessionDialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(237, 340, 291, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.test_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.test_pushButton.setObjectName("test_pushButton")
        self.horizontalLayout.addWidget(self.test_pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget1)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)

        self.retranslateUi(HkuEditSessionDialog)
        self.buttonBox.accepted.connect(HkuEditSessionDialog.accept)
        self.buttonBox.rejected.connect(HkuEditSessionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(HkuEditSessionDialog)

    def retranslateUi(self, HkuEditSessionDialog):
        _translate = QtCore.QCoreApplication.translate
        HkuEditSessionDialog.setWindowTitle(_translate("HkuEditSessionDialog", "Dialog"))
        self.host_label.setText(_translate("HkuEditSessionDialog", "Host/ip:"))
        self.port_label.setText(_translate("HkuEditSessionDialog", "Port:"))
        self.user_label.setText(_translate("HkuEditSessionDialog", "User:"))
        self.password_label.setText(_translate("HkuEditSessionDialog", "Password:"))
        self.remark_label.setText(_translate("HkuEditSessionDialog", "Remark:"))
        self.test_pushButton.setText(_translate("HkuEditSessionDialog", "Test connect"))
