# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_HkuEditXueqiuAccountDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_XueqiuAccountDialog(object):
    def setupUi(self, XueqiuAccountDialog):
        XueqiuAccountDialog.setObjectName("XueqiuAccountDialog")
        XueqiuAccountDialog.resize(487, 406)
        self.buttonBox = QtWidgets.QDialogButtonBox(XueqiuAccountDialog)
        self.buttonBox.setGeometry(QtCore.QRect(120, 350, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(XueqiuAccountDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(29, 29, 431, 301))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.td_id_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.td_id_lineEdit.setEnabled(False)
        self.td_id_lineEdit.setObjectName("td_id_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.td_id_lineEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.name_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.name_lineEdit.setMaxLength(100)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name_lineEdit)
        self.portfolio_code_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.portfolio_code_lineEdit.setMaxLength(100)
        self.portfolio_code_lineEdit.setObjectName("portfolio_code_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.portfolio_code_lineEdit)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.portfolio_market_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.portfolio_market_lineEdit.setMaxLength(100)
        self.portfolio_market_lineEdit.setObjectName("portfolio_market_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.portfolio_market_lineEdit)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cookies_textEdit = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.cookies_textEdit.setObjectName("cookies_textEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cookies_textEdit)

        self.retranslateUi(XueqiuAccountDialog)
        self.buttonBox.accepted.connect(XueqiuAccountDialog.accept)
        self.buttonBox.rejected.connect(XueqiuAccountDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(XueqiuAccountDialog)

    def retranslateUi(self, XueqiuAccountDialog):
        _translate = QtCore.QCoreApplication.translate
        XueqiuAccountDialog.setWindowTitle(_translate("XueqiuAccountDialog", "XueQiu Account Setting"))
        self.label.setText(_translate("XueqiuAccountDialog", "Account id"))
        self.label_2.setText(_translate("XueqiuAccountDialog", "Account name"))
        self.label_4.setText(_translate("XueqiuAccountDialog", "Portfolio market"))
        self.label_5.setText(_translate("XueqiuAccountDialog", "Cookies"))
        self.label_3.setText(_translate("XueqiuAccountDialog", "Portfolio code"))
